version: "3.8"

services:
  paperlessdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperless
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: paperlessdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: paperless-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  paperless-rest:
    build:
      context: ./apps/paperless-rest
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: paperless-rest
    depends_on:
      paperlessdb:
          condition: service_healthy

  paperless-ui:
    build:
      context: ./apps/paperless-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: paperless-ui
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx-config:
    file: nginx/nginx.conf

volumes:
  db-data:
