version: "3.8"

services:
  paperless-rest:
    build:
      context: ./apps/paperless-rest
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: paperless-rest

  paperless-ui:
    build:
      context: ./apps/paperless-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    container_name: paperless-ui

configs:
  nginx-config:
    file: nginx/nginx.conf