spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin-password

minio:
  access:
    name: admin
    secret: admin-password
  endpoint: minio

tesseract:
  data: /usr/share/tesseract-ocr/4.00/tessdata